# MAKER-OPTIMIZED STRATEGY
# FOCUS: Maximize 0% maker fills, minimize 2.4bps taker hedges

strategy: skew_mid_spread
max_snapshots: 10000
log_level: INFO
log_throttle: 10
print_interval: 5000

# MINIMIZE TAKER HEDGING
momentum_filter: true       
momentum_lookback: 4        # More conservative hedging
post_only: true             

inventory_band: 3.0         # CHANGED: larger band to avoid frequent hedging
max_inventory: 20           
sharpe_denominator: max_inventory

hedge_fraction: 0.4         # CHANGED: minimal hedging when it happens

# Keep realistic market conditions
order_ttl: 0.6 
hold_time: 0.5              # CHANGED: faster updates for better inventory management
cancel_if_behind: true
max_ticks_away: 5           # CHANGED: tighter control
latency_mean_ms: 15         
latency_std_ms: 5
competition_intensity: 0.9  
min_competitors: 3          
max_competitors: 8          
competitor_order_size: 0.05 
funding_interval: 8.0

# EXTREME INVENTORY SKEWING - let the strategy balance itself
strategy_kwargs:
  size_base: 0.4            # CHANGED: reasonable base size
  k_vol: 3.0                # CHANGED: tighter spreads for better fills
  extra_spread_ticks: 15    # CHANGED: minimal padding
  gamma: 0.50               # CHANGED: very aggressive inventory skewing
  gradient_threshold: 1.0   # CHANGED: very sensitive to thin books
  gradient_penalty_ticks: 3 # CHANGED: strong penalty for thin books
  gamma_imb: 1.0            # CHANGED: very strong imbalance response
  gamma_inv_scale: 6.0      # CHANGED: extreme inventory-based skewing
  gamma_vol_scale: 2.0      # CHANGED: strong volatility response
  gamma_cap_factor: 10.0    # CHANGED: allow very high gamma when needed
  size_min_factor: 0.05     # CHANGED: very small size when inventory high
  size_exp: 3.5             # CHANGED: aggressive sizing curve
  use_ticks: true           # Use tick-based gamma for precision
  clamp_ticks: 2            # CHANGED: keep heavy side close to touch

data_dir: data/converted/binance
output_dir: ./results

maker_fee: 0.0              # FREE MONEY!
taker_fee: 0.00024          # EXPENSIVE - avoid at all costs