# --- Fixed parameters -----------------------------------
gamma_cap_factor: [5.0]
gamma_imb:  [0.5]
size_base:       [0.005]
size_min_factor: [0.3]
size_exp:        [2]
max_inventory:   [0.05]
order_ttl:       [0.6]

# --- sweep parameters -----------------------------------
k_vol:      [0.8, 1.0, 1.3]
gamma:      [0.05, 0.10]
gamma_inv_scale: [1, 2, 4]
gamma_vol_scale: [0, 1]   


