# --- spread/skew params (fixed for this sweep) ----------
k_vol:      [1.3]          # keep constant
gamma:      [0.10]         # base Î³
gamma_inv_scale: [4.0]     # keep constant
gamma_vol_scale: [2.0]     # keep constant
gamma_cap_factor: [5.0]    # keep constant
gamma_imb:  [0.5]          # keep constant

# --- sweep parameters -----------------------------------
size_base:       [0.005, 0.01, 0.02, 0.04]
size_min_factor: [0.1, 0.2, 0.3]
size_exp:        [1, 2, 3]
max_inventory:   [0.05, 0.1, 0.2]
order_ttl:       [0.4, 0.6, 0.8, 1.0]